default: &default
  adapter: postgresql
  encoding: unicode
  username: root
  password: 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ur_pets_life_development

test:
  <<: *default
  database: ur_pets_life_test

production:
  <<: *default
  database: ur_pets_life_production
